### ISSUE TITLE
feature: Get the secret containing the Kubeconfig to connect to a control plane from the status in the ControlPlane object

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubeflex#110]
### Feature Description

For clients that interact mainly with the ControlPlane CR, it would be helpful to get a reference there to the secret containing the Kubeconfig to access that control plane.

### Proposed Solution

Add a `SecretRef` in the status of ControlPlane, so that for an active ControlPlane status will show the following:

```
status:
  secretRef:
     name: admin-kubeconfig
     namespace: cp1-system 
  conditions:
  - lastTransitionTime: "2023-11-10T16:07:42Z"
    lastUpdateTime: "2023-11-10T16:07:42Z"
    message: ""
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-11-10T16:07:42Z"
    lastUpdateTime: "2023-11-10T16:07:42Z"
    message: ""
    reason: ReconcileSuccess
    status: "True"
    type: Synced
```    

### Want to contribute?

- [x] I would like to work on this issue.
