### ISSUE TITLE
feature:  add key to secretref for kubeconfig in controlplane

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubeflex#117]
### Feature Description

Currently the secretref in controlplane provides the secret name and namespace. E.g.,

```
 secretRef:
    name: vc-vcluster
    namespace: imbs1-system
```    

However, some control plane like vcluster use a different name for the key used for kubeconfig - e.g., `config`

### Proposed Solution

Add the key for kubeconfig in secretref, eg.,:

```
 secretRef:
    name: vc-vcluster
    namespace: imbs1-system
    key: config
```  

### Want to contribute?

- [x] I would like to work on this issue.
