### ISSUE TITLE
bug: Fix util.GroupVersionKindToResource vs. stale api service error

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubeflex#160]
### Describe the bug

If user adds manually an APIService, it may break functions using clientset.Discovery().ServerPreferredResources(). The discovery returns an error such as:

```
unable to retrieve the complete list of server APIs: example.my/v1090: stale GroupVersion discovery: example.my/v1090"}
```

but in reality it's able to retrieve a partial list. 

### Steps To Reproduce

1. create a WDS
2. apply an APIservice vs. that WDS such as:
```
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1090.example.my
spec:
  group: example.my
  groupPriorityMinimum: 360
  service:
    name: my-service
    namespace: my-example
  version: v1090
  versionPriority: 42
```
3. Verify that it breaks util.GroupVersionKindToResource

  

### Expected Behavior

Should ignore the stale API resource. 

### Additional Context

Suggested fix:

```
const (
	UnableToRetrieveCompleteAPIListError = "unable to retrieve the complete list of server APIs"
)

	resourceList, err := clientset.Discovery().ServerPreferredResources()
	if err != nil {
		// ignore the error caused by a stale API service
		if !strings.Contains(err.Error(), UnableToRetrieveCompleteAPIListError) {
			return nil, err
		}
	}
	
```
