### ISSUE TITLE
feature:  Add additional flags to the `manager` command

### ISSUE THREAD

**Issue by francostellari** [kubestellar/kubeflex#177]
### Feature Description

Add additional flags to the `manager` command to enable the automatic creation of logical spaces during helm installation, similarly to `kflex create` command.

### Proposed Solution

For example `manager --create <space1> [--type <type1>] [-p  <post-create-hook1>] --create <space2> [--type <type2>] [-p  <post-create-hook2>]`

This would then be supported in the chart/values.yaml such as:

```yaml
spaces:
 - name: space1
   type: type1
   p: post-create-hook1
 - name: space2
   type: type2
   p: post-create-hook2
```

### Want to contribute?

- [ ] I would like to work on this issue.
