### ISSUE TITLE
feature:  add option to set variables with the post-install-hooks

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubeflex#215]
### Feature Description

This feature would help removing the circular dependency issue in KubeStellar when using the Post Create Hook method. The idea is to extend the use of templating for variables substitution in the PCH, and have an option to pass those variables through the ControlPlane CR.

### Proposed Solution

1. Update the CR for ControlPlane to allow to specify variables for post-create-hooks:
```yaml
apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: ControlPlane
metadata:
  name: wds1
spec:
  backend: shared
  postCreateHook: kubestellar
  postCreateHookVars:
       MyTag: "1.36"
       MyVar: some value
  type: k8s
```
Note: the proposed change is backward compatible. We could also make it non-backward compatible by using a structured config under `postCreateHook`
2. The post create hook allows to include the variables defined in the CP, for example:
```yaml
apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: PostCreateHook
metadata:
  name: hello
spec:
  templates:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: hello
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: public.ecr.aws/docker/library/busybox:"{{MyTag}}"
            command: ["echo",  "Hello", "World"]
          restartPolicy: Never
      backoffLimit: 1
```  
3. The kflex CLI is extended to pass the post create hook vars with the `--set` flag, for example:
```shell
kflex create hello -p hello --set MyTag=1.36
```

 

 

### Want to contribute?

- [ ] I would like to work on this issue.
