### ISSUE TITLE
task: use `AssignControlPlaneToContext` function in `kflex create`

### ISSUE THREAD

**Issue by rxinui** [kubestellar/kubeflex#436]
## Description

Following the implementation of #435 

Make use of c function in `kflex create`. Therefore, when running the following:

`kflex create mysupercp` 

the kubeconfig file will has the following context entry:

```yaml
- context:
    cluster: mysupercp-cluster
    extensions:
    - extension:
        data:
          controlplane-name: "mysupercp"           # result of `AssignControlPlaneToContext`
        metadata:
          creationTimestamp: "2025-06-09T23:00:55Z"
          name: kubeflex
      name: kubeflex
    user: mysupercp-admin
  name: mysupercp
```

## Expected

- [ ] Ensure `kflex create` command implement correcty `AssignControlPlaneToContext`
- [ ] Update `test/e2e/manage-type-k8s.sh`
  - [ ] Verify that E2E tests on CI are all green, else fix it
